export const mocksGetWeathers = {
  data: {
    weathers: [
      {
        id: "2267056",
        city: "Lisbon District",
        coordinates: {
          longitude: -9.1333,
          latitude: 39,
        },
        currentWeather: {
          status: "Clouds",
          description: "broken clouds",
          icon: "http://openweathermap.org/img/wn/04n@4x.png",
          temp: 11,
          feelsLike: 8,
          tempMin: 11,
          tempMax: 11,
          pressure: 1029,
          humidity: 93,
          windSpeed: 4.12,
        },
      },
      {
        id: "2267094",
        city: "Leiria",
        coordinates: {
          longitude: -8.8333,
          latitude: 39.6667,
        },
        currentWeather: {
          status: "Clouds",
          description: "overcast clouds",
          icon: "http://openweathermap.org/img/wn/04n@4x.png",
          temp: 9,
          feelsLike: 8,
          tempMin: 9,
          tempMax: 10,
          pressure: 1030,
          humidity: 93,
          windSpeed: 1.03,
        },
      },
      {
        id: "2740636",
        city: "Coimbra",
        coordinates: {
          longitude: -8.4167,
          latitude: 40.2,
        },
        currentWeather: {
          status: "Clouds",
          description: "overcast clouds",
          icon: "http://openweathermap.org/img/wn/04n@4x.png",
          temp: 6,
          feelsLike: 5,
          tempMin: 3,
          tempMax: 10,
          pressure: 1030,
          humidity: 93,
          windSpeed: 1.03,
        },
      },
      {
        id: "2735941",
        city: "Porto",
        coordinates: {
          longitude: -8.3333,
          latitude: 41.25,
        },
        currentWeather: {
          status: "Clear",
          description: "clear sky",
          icon: "http://openweathermap.org/img/wn/01n@4x.png",
          temp: 3,
          feelsLike: 0,
          tempMin: 3,
          tempMax: 4,
          pressure: 1030,
          humidity: 93,
          windSpeed: 2.06,
        },
      },
      {
        id: "2268337",
        city: "Faro",
        coordinates: {
          longitude: -8.1667,
          latitude: 37.2,
        },
        currentWeather: {
          status: "Clear",
          description: "clear sky",
          icon: "http://openweathermap.org/img/wn/01n@4x.png",
          temp: 5,
          feelsLike: 1,
          tempMin: 5,
          tempMax: 5,
          pressure: 1028,
          humidity: 93,
          windSpeed: 3.09,
        },
      },
    ],
  },
};
